"""Generated command catalogue from DOCs/api_documentation.pdf."""

from __future__ import annotations

from typing import Final

from .models import CommandSpec

_COMMAND_DATA: Final = (
    ("Billing_Autorenew_GetAll", (), ("currency", "domain")),
    ("Billing_Autorenew_SetNoRenewable", ("id",), ()),
    ("Billing_Autorenew_SetOff", ("id",), ()),
    ("Billing_Autorenew_SetOn", ("id", "paymentMethodId", "periodUnit"), ("period",)),
    (
        "Billing_Buy_Domain",
        ("domain", "period", "contacts"),
        ("dnss", "whoisProtection", "extraData"),
    ),
    (
        "Billing_Buy_DomainUsingContactsIds",
        ("domain", "period", "contacts"),
        ("dnss", "whoisProtection", "extraData"),
    ),
    ("Billing_Buy_Hosting", ("hosting", "period", "hostingType", "serverOs"), ()),
    ("Billing_Buy_Multihosting", ("period", "serverOs"), ()),
    ("Billing_Buy_Sms", ("account", "credit"), ()),
    (
        "Billing_Buy_Vps_Managed_Linux",
        ("type", "period", "vcpusCount", "diskType", "diskImage"),
        (),
    ),
    (
        "Billing_Buy_Vps_Managed_Windows",
        ("type", "period", "vcpusCount", "diskType"),
        (),
    ),
    (
        "Billing_Buy_Vps_Unmanaged_Linux",
        ("type", "period", "vcpusCount", "diskType", "diskImage"),
        (),
    ),
    (
        "Billing_Buy_Vps_Unmanaged_Windows",
        ("type", "period", "vcpusCount", "diskType", "diskImage"),
        (),
    ),
    ("Billing_GetConfigurableVpsOptions", (), ()),
    ("Billing_Help_DomainExtraData", ("action",), ("tld",)),
    ("Billing_NoRenewable_GetAll", (), ()),
    ("Billing_NoRenewable_SetRenewable", ("id",), ()),
    ("Billing_Period_Domain", ("action",), ("tld",)),
    ("Billing_Period_Hosting", ("action",), ()),
    ("Billing_Period_Multihosting", ("action",), ()),
    ("Billing_Period_Vps", ("action",), ()),
    (
        "Billing_Price_Domain",
        ("tld", "period", "action"),
        ("whoisProtection", "currency"),
    ),
    (
        "Billing_Price_Hosting",
        ("period", "hostingType", "serverOs", "action"),
        ("currency",),
    ),
    ("Billing_Price_Multihosting", ("period", "serverOs", "action"), ("currency",)),
    ("Billing_Price_Sms", ("credit", "action"), ("currency",)),
    (
        "Billing_Price_Vps_Managed_Linux",
        ("type", "period", "vcpusCount", "diskType", "action"),
        ("currency",),
    ),
    (
        "Billing_Price_Vps_Managed_Windows",
        ("type", "period", "vcpusCount", "diskType", "action"),
        ("currency",),
    ),
    (
        "Billing_Price_Vps_Unmanaged_Linux",
        ("type", "period", "vcpusCount", "diskType", "action"),
        ("currency",),
    ),
    (
        "Billing_Price_Vps_Unmanaged_Windows",
        ("type", "period", "vcpusCount", "diskType", "diskImage", "action"),
        ("currency",),
    ),
    ("Billing_Renew_Domain", ("domain", "period"), ("whoisProtection",)),
    ("Billing_Renew_Hosting", ("hosting", "period"), ()),
    ("Billing_Renew_Multihosting", ("serverName", "period"), ()),
    ("Billing_Renew_Sms", ("account", "credit"), ()),
    ("Billing_Renew_Vps", ("serverName", "period"), ()),
    (
        "Billing_Transfer_Domain",
        ("domain", "period"),
        ("contacts", "dnss", "whoisProtection"),
    ),
    ("Billing_Transfer_GetRequirements", (), ()),
    ("Dedicated_Control_GetApacheProcesses", ("serverName",), ()),
    ("Dedicated_Control_GetCpuLoadByHosting", ("serverName",), ()),
    ("Dedicated_Control_GetMysqlProcesses", ("serverName",), ()),
    ("Dedicated_Control_GetSystemLoad", ("serverName",), ()),
    ("Dedicated_Control_GetSystemStatus", ("serverName",), ()),
    ("Dedicated_Control_GetWebserverStatus", ("serverName",), ()),
    ("Dedicated_Control_KillMysqlProcess", ("serverName", "pid"), ()),
    ("Dedicated_ForVps_GetServerInfo", ("serverName",), ()),
    ("Dedicated_ForVps_GetTicketStatus", ("serverName", "ticketId"), ()),
    ("Dedicated_ForVps_Vps_Activate", ("serverName", "vpsHostname"), ()),
    (
        "Dedicated_ForVps_Vps_Create_Managed",
        ("serverName", "diskImage", "vcpusCount", "ram", "diskSpace"),
        ("alias", "description", "transferLimit"),
    ),
    (
        "Dedicated_ForVps_Vps_Create_Unmanaged",
        ("serverName", "diskImage", "vcpusCount", "ram", "diskSpace"),
        ("alias", "description", "transferLimit"),
    ),
    ("Dedicated_ForVps_Vps_Deactivate", ("serverName", "vpsHostname"), ()),
    ("Dedicated_ForVps_Vps_Delete", ("serverName", "vpsHostname"), ()),
    ("Dedicated_ForVps_Vps_GetAll", ("serverName",), ()),
    ("Dedicated_ForVps_Vps_GetTypes", ("serverName",), ()),
    (
        "Dedicated_ForVps_Vps_Update",
        ("serverName", "vpsHostname", "vcpusCount", "ram", "diskSpace"),
        ("alias", "description", "transferLimit"),
    ),
    ("Dedicated_GetBandwidthConsumption", ("serverName", "month", "year"), ()),
    ("Dedicated_GetDataTransferInfo", ("serverName",), ()),
    ("Dedicated_GetLicenses", ("serverName",), ()),
    ("Dedicated_GetMonitorizedPorts", ("serverName",), ()),
    ("Dedicated_GetServerInfo", ("serverName",), ()),
    ("Dedicated_GetSpaceAndTransferReportPerHosting", ("serverName",), ()),
    ("Dedicated_GetTransferValue", ("serverName",), ()),
    ("Dedicated_GetUsedSpace", ("serverName",), ()),
    ("Dedicated_HostingSetup_Create", ("serverName", "setupName", "options"), ()),
    ("Dedicated_HostingSetup_Delete", ("serverName", "setupName"), ()),
    ("Dedicated_HostingSetup_Get", ("serverName", "setupName"), ()),
    ("Dedicated_HostingSetup_GetAll", ("serverName",), ()),
    ("Dedicated_HostingSetup_GetCustomSetups", ("serverName",), ()),
    ("Dedicated_HostingSetup_GetDhSetups", ("serverName",), ()),
    ("Dedicated_HostingSetup_GetOptions", ("serverName",), ()),
    ("Dedicated_HostingSetup_Update", ("serverName", "setupName", "options"), ()),
    ("Dedicated_Hosting_Activate", ("serverName", "domainName"), ()),
    ("Dedicated_Hosting_ChangeSetup", ("serverName", "domainName", "setupName"), ()),
    (
        "Dedicated_Hosting_Create",
        ("serverName", "domainName", "setupName", "setZones"),
        (),
    ),
    ("Dedicated_Hosting_Deactivate", ("serverName", "domainName"), ()),
    ("Dedicated_Hosting_Delete", ("serverName", "domainName"), ()),
    ("Dedicated_Hosting_GetAll", ("serverName",), ("onlyActiveHostings",)),
    ("Dedicated_Hosting_GetSetupName", ("serverName", "domainName"), ()),
    ("Dedicated_Hosting_GetSpace", ("serverName", "domainName"), ()),
    ("Dedicated_Kvm_Get", ("serverName",), ()),
    ("Dedicated_Kvm_Mount", ("serverName",), ()),
    ("Dedicated_Kvm_Unmount", ("serverName",), ()),
    ("Dedicated_MailReport_Get", ("serverName",), ()),
    ("Dedicated_MailReport_Set", ("serverName", "emailTo", "periodicity"), ()),
    ("Dedicated_MailReport_SetOff", ("serverName",), ()),
    ("Dedicated_Monitorization_Activate", ("serverName", "emails"), ()),
    ("Dedicated_Monitorization_Deactivate", ("serverName",), ()),
    ("Dedicated_Monitorization_Get", ("serverName",), ()),
    ("Dedicated_Nfs_Get", ("serverName",), ()),
    ("Dedicated_PowerStatus_Restart", ("serverName",), ()),
    (
        "Dedicated_Services_ChangeStatus",
        ("serverName", "serviceName", "serviceAction"),
        (),
    ),
    ("Dedicated_Services_GetAll", ("serverName",), ()),
    ("DomainVerification_GetPending", (), ()),
    ("Domain_CheckForRegister", ("domain",), ()),
    ("Domain_CheckForTransfer", ("domain",), ()),
    ("Domain_Contacts_Get", ("domain", "contactType"), ()),
    ("Domain_Contacts_GetAll", ("domain",), ()),
    ("Domain_Contacts_GetRegistrantVerificationInfo", ("domain",), ()),
    ("Domain_Contacts_Set", ("domain", "contactType", "contacts"), ()),
    ("Domain_Contacts_SetAll", ("domain", "contacts"), ()),
    ("Domain_Dnss_Get", ("domain",), ()),
    ("Domain_Dnss_Set", ("domain", "dnss"), ()),
    ("Domain_GetAuthcode", ("domain",), ()),
    ("Domain_GetExpirationDate", ("domain",), ()),
    ("Domain_GetInfoDomain", ("domain",), ()),
    ("Domain_GetRegistrationDate", ("domain",), ()),
    ("Domain_GetRenovationDate", ("domain",), ()),
    ("Domain_NameServer_Delete", ("domain", "hostname"), ()),
    ("Domain_NameServer_GetAll", ("domain",), ()),
    ("Domain_NameServer_Modify", ("domain", "hostname", "ip"), ()),
    ("Domain_NameServer_Register", ("domain", "hostname", "ip"), ()),
    ("Domain_PanelIndependentAccess_SetPassword", ("domain", "newPassword"), ()),
    ("Domain_Parking_Get", ("domain",), ()),
    ("Domain_Parking_Set", ("domain",), ("title", "description")),
    ("Domain_Redirection_Delete", ("domain",), ("removeAll",)),
    ("Domain_Redirection_Get", ("domain",), ()),
    ("Domain_Redirection_GetAll", ("domain",), ()),
    ("Domain_Redirection_Set301", ("domain", "url"), ("host",)),
    (
        "Domain_Redirection_SetFrame",
        ("domain", "url"),
        ("title", "description", "keywords", "favicon", "viewport"),
    ),
    ("Domain_Redirection_SetFrameSimple", ("domain", "url"), ("host",)),
    ("Domain_Redirection_SetStd", ("domain", "url"), ("host",)),
    ("Domain_Status_Get", ("domain",), ()),
    ("Domain_Status_IsLocked", ("domain",), ()),
    ("Domain_Status_Lock", ("domain",), ()),
    ("Domain_Status_Unlock", ("domain",), ()),
    ("Domain_Test", ("domain",), ("optional",)),
    ("Domain_Transfer_Cancel", ("domain",), ()),
    ("Domain_Transfer_GetAuthcode", ("domain",), ()),
    ("Domain_Transfer_GetStatus", ("domain",), ()),
    ("Domain_Transfer_Restart", ("domain",), ()),
    ("Domain_Transfer_SetAuthcode", ("domain", "newAuthcode"), ()),
    ("Domain_UrlShortener_Activate", ("domain",), ()),
    ("Domain_UrlShortener_Create", ("domain", "url"), ("title",)),
    ("Domain_UrlShortener_Deactivate", ("domain",), ()),
    ("Domain_UrlShortener_Delete", ("domain", "keyword"), ()),
    ("Domain_UrlShortener_GetAll", ("domain",), ()),
    ("Domain_WhoisPrivacy_Get", ("domain",), ()),
    ("Domain_WhoisPrivacy_Set", ("domain",), ("redirectionEmail", "enable")),
    ("Domain_Zone_AddTypeA", ("domain", "hostname", "ip"), ()),
    ("Domain_Zone_AddTypeAAAA", ("domain", "hostname", "ip"), ()),
    ("Domain_Zone_AddTypeAname", ("domain", "destinationHostname"), ()),
    ("Domain_Zone_AddTypeCname", ("domain", "hostname", "destinationHostname"), ()),
    ("Domain_Zone_AddTypeFrame", ("domain", "hostname", "destinationUrl"), ()),
    ("Domain_Zone_AddTypeMX", ("domain", "priority", "value"), ("host",)),
    ("Domain_Zone_AddTypeMXDetailedEmail", ("domain", "mxNumber", "hostname"), ()),
    ("Domain_Zone_AddTypeMXS", ("domain", "hostname", "ip"), ()),
    (
        "Domain_Zone_AddTypeSRV",
        ("domain", "service", "protocol", "priority", "weight", "port", "destination"),
        (),
    ),
    ("Domain_Zone_AddTypeTXT", ("domain", "hostname", "text"), ()),
    ("Domain_Zone_AddTypeURL", ("domain", "hostname", "destinationUrl"), ()),
    ("Domain_Zone_AddTypeURL301", ("domain", "hostname", "destinationUrl"), ()),
    ("Domain_Zone_Delete", ("domain", "hostname"), ()),
    ("Domain_Zone_DeleteAll", ("domain", "type"), ()),
    ("Domain_Zone_DeleteTypeA", ("domain", "hostname", "ip"), ()),
    ("Domain_Zone_DeleteTypeAAAA", ("domain", "hostname", "ip"), ()),
    ("Domain_Zone_DeleteTypeAname", ("domain",), ()),
    ("Domain_Zone_DeleteTypeCname", ("domain", "hostname"), ()),
    ("Domain_Zone_DeleteTypeFrame", ("domain",), ("hostname",)),
    ("Domain_Zone_DeleteTypeMX", ("domain", "host", "address"), ()),
    ("Domain_Zone_DeleteTypeSPF", ("domain", "hostname"), ("value",)),
    (
        "Domain_Zone_DeleteTypeSRV",
        ("domain", "service", "protocol", "priority", "weight", "port", "destination"),
        (),
    ),
    ("Domain_Zone_DeleteTypeTXT", ("domain", "hostname"), ("value",)),
    ("Domain_Zone_DeleteTypeURL", ("domain",), ("hostname",)),
    ("Domain_Zone_DeleteTypeURL301", ("domain",), ("hostname",)),
    ("Domain_Zone_GetAll", ("domain",), ("orderBy",)),
    ("Domain_Zone_GetTypeA", ("domain",), ()),
    ("Domain_Zone_GetTypeAAAA", ("domain",), ()),
    ("Domain_Zone_GetTypeAname", ("domain",), ()),
    ("Domain_Zone_GetTypeCname", ("domain",), ()),
    ("Domain_Zone_GetTypeFrame", ("domain",), ()),
    ("Domain_Zone_GetTypeMX", ("domain",), ()),
    ("Domain_Zone_GetTypeSPF", ("domain",), ()),
    ("Domain_Zone_GetTypeSRV", ("domain",), ()),
    ("Domain_Zone_GetTypeTXT", ("domain",), ()),
    ("Domain_Zone_GetTypeURL", ("domain",), ()),
    ("Domain_Zone_GetTypeURL301", ("domain",), ()),
    ("Domain_Zone_UpdateTypeA", ("domain", "hostname", "ip"), ("oldIp",)),
    ("Domain_Zone_UpdateTypeAAAA", ("domain", "hostname", "ip"), ("oldIp",)),
    (
        "Domain_Zone_UpdateTypeAname",
        ("domain", "destinationHostname", "oldDestinationHostname"),
        (),
    ),
    ("Domain_Zone_UrlShortener_Activate", ("domain", "hostname"), ()),
    ("Domain_Zone_UrlShortener_Create", ("domain", "url"), ("title",)),
    ("Domain_Zone_UrlShortener_Deactivate", ("domain",), ()),
    ("Domain_Zone_UrlShortener_Delete", ("domain", "keyword"), ()),
    ("Domain_Zone_UrlShortener_GetAll", ("domain",), ()),
    (
        "Hosting_Backup_Database_GetTables",
        ("hosting", "date", "databaseName", "databaseType"),
        (),
    ),
    ("Hosting_Backup_GetDatabases", ("hosting", "date"), ()),
    ("Hosting_Backup_GetEmailAccounts", ("hosting", "date"), ()),
    ("Hosting_Backup_GetResources", ("hosting", "date"), ("folderPath",)),
    ("Hosting_Backup_GetStatus", ("hosting",), ()),
    (
        "Hosting_Backup_Restore_Database",
        ("hosting", "date", "databaseName", "databaseType", "notificationEmail"),
        (),
    ),
    (
        "Hosting_Backup_Restore_Database_Tables",
        (
            "hosting",
            "date",
            "databaseName",
            "databaseType",
            "tables",
            "notificationEmail",
        ),
        (),
    ),
    (
        "Hosting_Backup_Restore_EmailAccounts",
        ("hosting", "date", "emailAccounts", "notificationEmail"),
        (),
    ),
    (
        "Hosting_Backup_Restore_Resource",
        ("hosting", "date", "resourcePath", "notificationEmail"),
        (),
    ),
    (
        "Hosting_Backup_Send_Database",
        ("hosting", "date", "databaseName", "databaseType", "email"),
        (),
    ),
    (
        "Hosting_Backup_Send_Database_Tables",
        ("hosting", "date", "databaseName", "databaseType", "tables", "email"),
        (),
    ),
    ("Hosting_Backup_Send_Resource", ("hosting", "date", "resourcePath", "email"), ()),
    ("Hosting_Certificate_ActivateLetsEncrypt", ("hosting",), ("subdomains",)),
    ("Hosting_Certificate_DeactivateLetsEncrypt", ("hosting",), ()),
    ("Hosting_Certificate_Install", ("hosting", "crt", "key", "crtIntermediate"), ()),
    ("Hosting_Certificate_Uninstall", ("hosting",), ()),
    ("Hosting_Ddbb_Access_GetAllMdb", ("hosting",), ()),
    ("Hosting_Ddbb_GetAll", ("hosting",), ()),
    (
        "Hosting_Ddbb_MariaDb_Create",
        ("hosting", "ddbbName", "userName", "userPassword"),
        (),
    ),
    ("Hosting_Ddbb_MariaDb_Delete", ("hosting", "ddbbName", "userName"), ()),
    ("Hosting_Ddbb_MariaDb_GetAll", ("hosting",), ()),
    (
        "Hosting_Ddbb_MariaDb_SetPassword",
        ("hosting", "ddbbName", "userName", "userPassword"),
        (),
    ),
    ("Hosting_Ddbb_MongoDb_Delete", ("hosting", "ddbbName"), ()),
    ("Hosting_Ddbb_MongoDb_GetAll", ("hosting",), ()),
    (
        "Hosting_Ddbb_MongoDb_SetPassword",
        ("hosting", "ddbbName", "userName", "userPassword"),
        (),
    ),
    ("Hosting_Ddbb_Mysql_BackupTask_Delete", ("hosting", "ddbbName"), ()),
    ("Hosting_Ddbb_Mysql_BackupTask_GetAll", ("hosting",), ()),
    ("Hosting_Ddbb_Mysql_BackupTask_Set", ("hosting", "ddbbName", "taskPeriod"), ()),
    ("Hosting_Ddbb_Mysql_Backup_Get", ("hosting", "ddbbName"), ()),
    ("Hosting_Ddbb_Mysql_Backup_Restore", ("hosting", "ddbbName", "file"), ()),
    (
        "Hosting_Ddbb_Mysql_Create",
        ("hosting", "ddbbName", "userName", "userPassword", "accessHost"),
        (),
    ),
    (
        "Hosting_Ddbb_Mysql_CreateWithIpAcl",
        ("hosting", "ddbbName", "userName", "userPassword", "accessHostIp"),
        (),
    ),
    ("Hosting_Ddbb_Mysql_Delete", ("hosting", "ddbbName"), ()),
    ("Hosting_Ddbb_Mysql_GetAclConfiguration", ("hosting", "ddbbName"), ()),
    ("Hosting_Ddbb_Mysql_GetAll", ("hosting",), ()),
    ("Hosting_Ddbb_Mysql_GetInfo", ("hosting", "ddbbName"), ()),
    ("Hosting_Ddbb_Mysql_SetHostAcl", ("hosting", "ddbbName", "hostname"), ()),
    ("Hosting_Ddbb_Mysql_SetIpAcl", ("hosting", "ddbbName", "ip"), ()),
    ("Hosting_Ddbb_Mysql_SetPassword", ("hosting", "ddbbName", "password"), ()),
    (
        "Hosting_Ddbb_Postgre_Create",
        ("hosting", "ddbbName", "userName", "userPassword"),
        (),
    ),
    ("Hosting_Ddbb_Postgre_Delete", ("hosting", "ddbbName"), ()),
    ("Hosting_Ddbb_Postgre_GetAll", ("hosting",), ()),
    (
        "Hosting_Ddbb_Postgre_SetPassword",
        ("hosting", "ddbbName", "userName", "userPassword"),
        (),
    ),
    (
        "Hosting_Ddbb_Sqlserver_Create",
        (
            "hosting",
            "ddbbName",
            "userName",
            "userPassword",
            "dataSize",
            "transactionsSize",
        ),
        ("accessFrom",),
    ),
    ("Hosting_Ddbb_Sqlserver_Delete", ("hosting", "ddbbName"), ()),
    ("Hosting_Ddbb_Sqlserver_GetAll", ("hosting",), ()),
    ("Hosting_Ddbb_Sqlserver_GetGlobalSpaceInfo", ("hosting",), ()),
    ("Hosting_Ddbb_Sqlserver_GetSpaceInfo", ("hosting",), ()),
    ("Hosting_Ddbb_Sqlserver_SetDataSize", ("hosting", "ddbbName", "dataSize"), ()),
    ("Hosting_Ddbb_Sqlserver_SetPassword", ("hosting", "ddbbName", "password"), ()),
    (
        "Hosting_Ddbb_Sqlserver_SetTransactionsSize",
        ("hosting", "ddbbName", "transactionsSize"),
        (),
    ),
    (
        "Hosting_Dsn_Access_Create",
        ("hosting", "ddbbName", "dsnName", "dsnDescription"),
        (),
    ),
    ("Hosting_Dsn_Access_Delete", ("hosting", "dsnName"), ()),
    ("Hosting_Dsn_Access_GetAll", ("hosting",), ()),
    (
        "Hosting_Dsn_Mysql_Create",
        ("hosting", "ddbbName", "dsnName", "dsnDescription"),
        (),
    ),
    ("Hosting_Dsn_Mysql_Delete", ("hosting", "dsnName"), ()),
    ("Hosting_Dsn_Mysql_GetAll", ("hosting",), ()),
    (
        "Hosting_Dsn_Sqlserver_Create",
        ("hosting", "ddbbName", "dsnName", "dsnDescription"),
        (),
    ),
    ("Hosting_Dsn_Sqlserver_Delete", ("hosting", "dsnName"), ()),
    ("Hosting_Dsn_Sqlserver_GetAll", ("hosting",), ()),
    ("Hosting_Email_Account_Activate", ("hosting", "account"), ()),
    ("Hosting_Email_Account_Create", ("hosting", "account", "password"), ()),
    ("Hosting_Email_Account_Deactivate", ("hosting", "account"), ()),
    ("Hosting_Email_Account_Delete", ("hosting", "account"), ()),
    ("Hosting_Email_Account_Empty", ("hosting", "account"), ()),
    ("Hosting_Email_Account_Get", ("hosting", "account"), ()),
    ("Hosting_Email_Account_GetAll", ("hosting",), ()),
    ("Hosting_Email_Account_GetCopyTo", ("hosting", "account"), ()),
    ("Hosting_Email_Account_RemoveCopyTo", ("hosting", "account"), ()),
    ("Hosting_Email_Account_SetCopyTo", ("hosting", "account", "destination"), ()),
    ("Hosting_Email_Account_SetPassword", ("hosting", "account", "password"), ()),
    ("Hosting_Email_Antispam_Activate", ("hosting",), ()),
    ("Hosting_Email_Antispam_AddDomainToBlacklist", ("hosting", "domain"), ()),
    ("Hosting_Email_Antispam_AddDomainToWhitelist", ("hosting", "domain"), ()),
    ("Hosting_Email_Antispam_Deactivate", ("hosting",), ()),
    ("Hosting_Email_Antispam_GetBlacklist", ("hosting",), ()),
    ("Hosting_Email_Antispam_GetConfig", ("hosting",), ()),
    ("Hosting_Email_Antispam_GetScore", ("hosting",), ()),
    ("Hosting_Email_Antispam_GetWhitelist", ("hosting",), ()),
    ("Hosting_Email_Antispam_RemoveDomainFromBlacklist", ("hosting", "domain"), ()),
    ("Hosting_Email_Antispam_RemoveDomainFromWhitelist", ("hosting", "domain"), ()),
    ("Hosting_Email_Antispam_SetConfig", ("hosting", "action"), ("list",)),
    ("Hosting_Email_Antispam_SetScore", ("hosting", "score"), ()),
    ("Hosting_Email_Antivirus_GetAttachedFilesFilters", ("hosting",), ()),
    ("Hosting_Email_Antivirus_GetConfig", ("hosting",), ()),
    ("Hosting_Email_Antivirus_SetConfig", ("hosting", "action"), ()),
    (
        "Hosting_Email_Antivirus_UpdateAttachedFileFilter",
        ("hosting", "tag", "action"),
        (),
    ),
    (
        "Hosting_Email_AutomaticDeletion_CreateRule",
        ("hosting", "alias", "scope", "antique", "ifExceedsSize"),
        (),
    ),
    ("Hosting_Email_AutomaticDeletion_DeleteRule", ("hosting", "alias"), ()),
    ("Hosting_Email_Autoresponse_Activate", ("hosting", "alias"), ()),
    (
        "Hosting_Email_Autoresponse_Create",
        ("hosting", "alias", "text"),
        ("excluded", "copy"),
    ),
    ("Hosting_Email_Autoresponse_Deactivate", ("hosting", "alias"), ()),
    ("Hosting_Email_Autoresponse_Delete", ("hosting", "alias"), ()),
    ("Hosting_Email_Autoresponse_Get", ("hosting", "alias"), ()),
    ("Hosting_Email_Dkim_Activate", ("hosting",), ()),
    ("Hosting_Email_Dkim_Deactivate", ("hosting",), ()),
    ("Hosting_Email_Dkim_Get", ("hosting",), ()),
    ("Hosting_Email_Dkim_IsActive", ("hosting",), ()),
    (
        "Hosting_Email_Filter_Create",
        ("hosting", "searchObject", "searchSubject", "action"),
        ("markLabel",),
    ),
    ("Hosting_Email_Filter_CreateForSpam", ("hosting", "action"), ("actionDestiny",)),
    ("Hosting_Email_Filter_Delete", ("hosting", "ruleId"), ()),
    ("Hosting_Email_Filter_GetAll", ("hosting",), ("country",)),
    ("Hosting_Email_Filter_GetGeolocalization", ("hosting",), ()),
    ("Hosting_Email_Filter_SetGeolocalization", ("hosting", "active"), ()),
    ("Hosting_Email_Redirection_ActivateCatchAll", ("hosting", "destination"), ()),
    ("Hosting_Email_Redirection_Create", ("hosting", "alias", "destination"), ()),
    ("Hosting_Email_Redirection_DeactivateCatchAll", ("hosting",), ()),
    ("Hosting_Email_Redirection_Delete", ("hosting", "alias"), ()),
    ("Hosting_Email_Redirection_Get", ("hosting", "alias"), ()),
    ("Hosting_Email_Redirection_GetAll", ("hosting",), ()),
    ("Hosting_Email_Redirection_Update", ("hosting", "alias", "destination"), ()),
    ("Hosting_Email_UsedSpace_Get", ("hosting",), ()),
    ("Hosting_Email_UsedSpace_GetPerAlias", ("hosting", "alias"), ()),
    ("Hosting_Ftp_Account_CmdStatus_GetCreate", ("hosting", "orderId"), ()),
    ("Hosting_Ftp_Account_CmdStatus_GetDelete", ("hosting", "orderId"), ()),
    ("Hosting_Ftp_Account_CmdStatus_GetSetPassword", ("hosting", "orderId"), ()),
    ("Hosting_Ftp_Account_CmdStatus_ListAll", ("hosting",), ()),
    ("Hosting_Ftp_Account_Create", ("hosting", "account", "password"), ("folder",)),
    ("Hosting_Ftp_Account_Delete", ("hosting", "account"), ()),
    ("Hosting_Ftp_Account_GetAll", ("hosting",), ()),
    ("Hosting_Ftp_Account_SetPassword", ("hosting", "account", "password"), ()),
    ("Hosting_Ftp_Activate", ("hosting",), ()),
    ("Hosting_Ftp_Deactivate", ("hosting",), ()),
    ("Hosting_Ftp_Get", ("hosting",), ()),
    ("Hosting_Ftp_GetAccountsLimit", ("hosting",), ()),
    ("Hosting_GetDaysWithBackups", ("hosting",), ("from",)),
    ("Hosting_GetInfo", ("hosting",), ()),
    ("Hosting_GetMailInfo", ("hosting",), ()),
    ("Hosting_Https_Activate", ("hosting",), ()),
    ("Hosting_Https_Deactivate", ("hosting",), ()),
    ("Hosting_Https_Get", ("hosting",), ()),
    (
        "Hosting_Import_ApplyForDdbb",
        ("hosting", "originDdbbName", "originUser", "originPassword"),
        (
            "create",
            "destinationDdbbName",
            "destinationUser",
            "destinationPassword",
            "notificationMail",
        ),
    ),
    (
        "Hosting_Import_ApplyForEmailAccountImap",
        ("hosting", "originEmailAddress", "originPassword", "originServer"),
        ("create", "destinationUser", "destinationPassword", "notificationMail"),
    ),
    (
        "Hosting_Import_ApplyForEmailAccountPop",
        ("hosting", "originEmailAddress", "originPassword", "originServer"),
        (
            "create",
            "destinationUser",
            "destinationPassword",
            "destinationFolder",
            "notificationMail",
        ),
    ),
    (
        "Hosting_Import_ApplyForFtp",
        ("originUser", "originPassword", "originServer"),
        (
            "originDirectory",
            "create",
            "destinationUser",
            "destinationPassword",
            "notificationMail",
        ),
    ),
    ("Hosting_Import_List", ("hosting",), ()),
    ("Hosting_Import_ListAll", ("hosting",), ()),
    ("Hosting_IsActive", ("hosting",), ()),
    ("Hosting_PanelIndependentAccess_SetPassword", ("hosting", "newPassword"), ()),
    ("Hosting_Php_ActivatePhpExecutionOnHtml", ("hosting",), ()),
    ("Hosting_Php_DeactivatePhpExecutionOnHtml", ("hosting",), ()),
    ("Hosting_Php_OverwritePhpIni", ("hosting", "text"), ()),
    ("Hosting_Php_OverwritePhpIniWithDefaults", ("hosting",), ()),
    ("Hosting_Php_PhpExecutionOnHtmlIsActive", ("hosting",), ()),
    ("Hosting_Php_SetVersion", ("hosting", "version"), ()),
    ("Hosting_Ssh_Activate", ("hosting",), ()),
    ("Hosting_Ssh_Deactivate", ("hosting",), ()),
    ("Hosting_Ssh_Get", ("hosting",), ()),
    ("Hosting_Subdomain_Create", ("hosting", "host"), ("directory", "ftpAccount")),
    ("Hosting_Subdomain_Delete", ("hosting", "host"), ()),
    ("Hosting_Subdomain_GetAll", ("hosting",), ()),
    ("Hosting_Test", ("hosting",), ("optional",)),
    ("Hosting_TlsMail_Activate", ("hosting",), ()),
    ("Hosting_TlsMail_Deactivate", ("hosting",), ()),
    ("Hosting_TlsMail_Get", ("hosting",), ()),
    ("Hosting_UrlShortener_Activate", ("hosting", "folder"), ()),
    ("Hosting_UrlShortener_Create", ("hosting", "url"), ("title",)),
    ("Hosting_UrlShortener_Deactivate", ("hosting",), ()),
    ("Hosting_UrlShortener_Delete", ("hosting", "keyword"), ()),
    ("Hosting_UrlShortener_GetAll", ("hosting",), ()),
    ("Housing_GetBandwidthConsumption", ("serverName", "month", "year"), ()),
    ("Housing_GetDataTransferInfo", ("serverName",), ()),
    ("Housing_GetServerInfo", ("serverName",), ()),
    ("Housing_GetTransferValue", ("serverName",), ()),
    ("Housing_Kvm_Get", ("serverName",), ()),
    ("Housing_Kvm_Mount", ("serverName",), ()),
    ("Housing_Kvm_Unmount", ("serverName",), ()),
    ("Housing_Monitorization_Activate", ("serverName", "emails"), ()),
    ("Housing_Monitorization_Deactivate", ("serverName",), ()),
    ("Housing_Monitorization_Get", ("serverName",), ()),
    ("Housing_PowerStatus_Restart", ("serverName",), ()),
    ("Import_GetStatus", ("importId",), ()),
    ("Multihosting_GetEmailAccountsNumber", ("serverName",), ()),
    ("Multihosting_GetInfo", ("serverName",), ()),
    ("Multihosting_GetLicenses", ("serverName",), ()),
    ("Multihosting_GetUsedSpace", ("serverName",), ()),
    ("Multihosting_GetUsedTransfer", ("serverName",), ()),
    ("Multihosting_HostingSetup_Create", ("serverName", "setupName", "options"), ()),
    ("Multihosting_HostingSetup_Delete", ("serverName", "setupName"), ()),
    ("Multihosting_HostingSetup_Get", ("serverName", "setupName"), ()),
    ("Multihosting_HostingSetup_GetAll", ("serverName",), ()),
    ("Multihosting_HostingSetup_GetOptions", ("serverName",), ()),
    ("Multihosting_HostingSetup_Update", ("serverName", "setupName", "options"), ()),
    ("Multihosting_Hosting_Activate", ("serverName", "domainName"), ()),
    ("Multihosting_Hosting_ChangeSetup", ("serverName", "domainName", "setupName"), ()),
    (
        "Multihosting_Hosting_Create",
        ("serverName", "domainName", "setupName", "setZones"),
        (),
    ),
    ("Multihosting_Hosting_Deactivate", ("serverName", "domainName"), ()),
    ("Multihosting_Hosting_Delete", ("serverName", "domainName"), ()),
    ("Multihosting_Hosting_GetAll", ("serverName",), ("onlyActiveHostings",)),
    ("Multihosting_Hosting_GetSpace", ("serverName", "domainName"), ()),
    ("Multihosting_MailReport_Get", ("serverName",), ()),
    ("Multihosting_MailReport_Set", ("serverName", "emailTo", "periodicity"), ()),
    ("Multihosting_MailReport_SetOff", ("serverName",), ()),
    ("Payment_Credit_GetDetailed", (), ()),
    ("Payment_Credit_GetTotal", (), ()),
    ("Payment_Credit_List", (), ()),
    ("Payment_Method_GetAll", (), ()),
    (
        "Reseller_AssociateServices",
        ("service", "family", "contactId"),
        ("notifyContact",),
    ),
    ("Reseller_DissociateServices", ("service", "family"), ()),
    ("Services_GetAllManagedServersNames", (), ()),
    ("Services_GetCloudServers", (), ()),
    ("Services_GetDedicatedServers", (), ()),
    ("Services_GetDomainTransfers", (), ()),
    ("Services_GetDomains", (), ()),
    ("Services_GetHostings", (), ()),
    ("Services_GetHousingServers", (), ()),
    ("Services_GetManagedCloudServers", (), ()),
    ("Services_GetManagedDedicatedServers", (), ()),
    ("Services_GetManagedVps", (), ()),
    ("Services_GetMultihostings", (), ()),
    ("Services_GetSms", (), ()),
    ("Services_GetUnmanagedCloudServers", (), ()),
    ("Services_GetUnmanagedDedicatedServers", (), ()),
    ("Services_GetUnmanagedVps", (), ()),
    ("Services_GetVps", (), ()),
    ("Sms_DeliveryList_Create", ("account", "name", "ids"), ()),
    ("Sms_DeliveryList_Delete", ("account", "name"), ()),
    ("Sms_DeliveryList_Get", ("account", "name"), ()),
    ("Sms_DeliveryList_GetAll", ("account",), ()),
    ("Sms_DeliveryList_GetPhones", ("account", "name"), ()),
    ("Sms_DeliveryList_Update", ("account", "name", "ids"), ()),
    ("Sms_GetCredit", ("account",), ()),
    ("Sms_GetSender", ("account",), ()),
    ("Sms_History_GetBulkSent", ("account", "start", "end"), ()),
    ("Sms_History_GetProgrammed", ("account", "start", "end"), ()),
    ("Sms_History_GetSent", ("account", "start", "end"), ()),
    ("Sms_PanelIndependentAccess_SetPassword", ("account", "newPassword"), ()),
    ("Sms_Phonebook_CreateContact", ("account", "name", "phoneNumber"), ()),
    ("Sms_Phonebook_DeleteContact", ("account", "id"), ()),
    ("Sms_Phonebook_GetAllContacts", ("account",), ()),
    ("Sms_Phonebook_UpdateContact", ("account", "id", "name", "phoneNumber"), ()),
    ("Sms_Programmed_Cancel", ("account", "id"), ()),
    ("Sms_Send_Bulk_Limited_Gsm7", ("account", "contents", "to", "from"), ("when",)),
    ("Sms_Send_Bulk_Limited_Unicode", ("account", "contents", "to", "from"), ("when",)),
    ("Sms_Send_Bulk_Long_Gsm7", ("account", "contents", "to", "from"), ("when",)),
    ("Sms_Send_Bulk_Long_Unicode", ("account", "contents", "to", "from"), ("when",)),
    ("Sms_SetUp", ("account",), ("alias", "sender")),
    ("System_GetApiVersion", (), ()),
    ("System_GetRequestTypes", (), ()),
    ("System_GetResponseTypes", (), ()),
    ("System_ListMethods", (), ()),
    ("System_MethodHelp", ("commandName",), ()),
    ("System_MethodSignature", ("commandName",), ()),
    ("System_TestSimulation", (), ()),
    ("User_Data_GetValidLegalForms", (), ()),
    ("User_Default_GetAdminContact", (), ()),
    ("User_Default_GetDnss", (), ()),
    ("User_Default_GetTechContact", (), ()),
    ("User_GetContactVerificationStatus", (), ("email", "phone", "tld")),
    ("User_GetInfo", (), ()),
    ("User_GetInvoicedAmount", (), ("startDate", "endDate")),
    ("User_GetLastLoginDate", (), ()),
    ("User_GetNotifications", (), ()),
    ("User_GetServices", (), ()),
    (
        "User_Secondary_Create",
        ("personalData", "contactData", "loginData"),
        ("companyData",),
    ),
    ("User_Secondary_Delete", ("userId",), ()),
    ("User_Secondary_GetAll", (), ()),
    (
        "User_Secondary_Update",
        ("idSecondaryUser", "personalData", "contactData", "loginData"),
        ("companyData",),
    ),
    ("User_SendContactVerification", ("contactId", "type"), ()),
    ("Vps_Control_GetApacheProcesses", ("serverName",), ()),
    ("Vps_Control_GetCpuLoadByHosting", ("serverName",), ()),
    ("Vps_Control_GetMysqlProcesses", ("serverName",), ()),
    ("Vps_Control_GetSystemLoad", ("serverName",), ()),
    ("Vps_Control_GetSystemStatus", ("serverName",), ()),
    ("Vps_Control_KillMysqlProcess", ("serverName", "pid"), ()),
    ("Vps_GetAllHostingsFullReport", ("serverName",), ()),
    ("Vps_GetBandwidthConsumption", ("serverName", "month", "year"), ()),
    ("Vps_GetDataTransferInfo", ("serverName",), ()),
    ("Vps_GetLicenses", ("serverName",), ()),
    ("Vps_GetMonitorizedPorts", ("serverName",), ()),
    ("Vps_GetServerInfo", ("serverName",), ()),
    ("Vps_GetSpaceAndTransferReportPerHosting", ("serverName",), ()),
    ("Vps_GetUsedSpace", ("serverName",), ()),
    ("Vps_HostingSetup_Create", ("serverName", "setupName", "options"), ()),
    ("Vps_HostingSetup_Delete", ("serverName", "setupName"), ()),
    ("Vps_HostingSetup_Get", ("serverName", "setupName"), ()),
    ("Vps_HostingSetup_GetAll", ("serverName",), ()),
    ("Vps_HostingSetup_GetOptions", ("serverName",), ()),
    ("Vps_HostingSetup_Update", ("serverName", "setupName", "options"), ()),
    ("Vps_Hosting_Activate", ("serverName", "domainName"), ()),
    ("Vps_Hosting_ChangeSetup", ("serverName", "domainName", "setupName"), ()),
    ("Vps_Hosting_Create", ("serverName", "domainName", "setupName", "setZones"), ()),
    ("Vps_Hosting_Deactivate", ("serverName", "domainName"), ()),
    ("Vps_Hosting_Delete", ("serverName", "domainName"), ()),
    ("Vps_Hosting_GetAll", ("serverName",), ("onlyActiveHostings",)),
    ("Vps_Hosting_GetSetupName", ("serverName", "domainName"), ()),
    ("Vps_MailReport_Get", ("serverName",), ()),
    ("Vps_MailReport_Set", ("serverName", "emailTo", "periodicity"), ()),
    ("Vps_MailReport_SetOff", ("serverName",), ()),
    ("Vps_Monitorization_Activate", ("serverName", "emails"), ()),
    ("Vps_Monitorization_Deactivate", ("serverName",), ()),
    ("Vps_Monitorization_Get", ("serverName",), ()),
    ("Vps_Nfs_Get", ("serverName",), ()),
    ("Vps_PowerStatus_ElectricRestart", ("serverName",), ()),
    ("Vps_PowerStatus_Get", ("serverName",), ()),
    ("Vps_PowerStatus_Pause", ("serverName",), ()),
    ("Vps_PowerStatus_Reactivate", ("serverName",), ()),
    ("Vps_PowerStatus_Restart", ("serverName",), ()),
    ("Vps_PowerStatus_Suspend", ("serverName",), ()),
    ("Vps_PowerStatus_TurnOff", ("serverName",), ()),
    ("Vps_PowerStatus_TurnOn", ("serverName",), ()),
    ("Vps_PowerStatus_Unpause", ("serverName",), ()),
    ("Vps_Services_ChangeStatus", ("serverName", "serviceName", "serviceAction"), ()),
    ("Vps_Services_GetAll", ("serverName",), ()),
)

COMMANDS: Final = {
    name: CommandSpec(name, frozenset(required), frozenset(optional))
    for name, required, optional in _COMMAND_DATA
}
